url: https://byrocketscience.github.io
baseurl: 

# Site settings
name: Rocket Science Web Studio
title: "Web Design | App Development | Rocket Science Web Studio in Norfolk, VA"
email: contact@byrocketscience.com
description: "Rocket Science Web Studio is a web design and app development agency located in Norfolk, VA that helps everyday people turn their ideas into finished and marketable products. We serve Norfolk, Virginia Beach, Chesapeake, and the rest of the United States."

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: 26A69A
  secondary: 00695C
  secondary-dark: 333

# Team names, titles and social links
people:
- name: David Jenkins
  pic: david
  position: Project Lead Developer
  social:
    - title: twitter
      url: https://twitter.com/boarderdav
    - title: facebook
      url: https://www.facebook.com/boarderdav
    - title: linkedin
      url: https://www.linkedin.com/in/davidjenkinspe

- name: O'Neill Mateo
  pic: jose
  position: Android and Web Developer
  social:
    - title: globe
      url: http://mateoj.com
    - title: google-plus
      url: https://plus.google.com/+JoseMateoA/
    - title: linkedin
      url: http://www.linkedin.com/in/josemateoa

- name: Jake Spracher
  pic: jake
  position: iOS and Web Developer
  social:
    - title: globe
      url: http://jakespracher.com
    - title: twitter
      url: https://twitter.com/jakespracher
    - title: linkedin
      url: http://www.linkedin.com/in/jakespracher

- name: Franck Tchouambou
  pic: franck
  position: Growth Hacker & Business Developer
  social:
    - title: twitter
      url: https://www.twitter.com/thyfranck
    - title: facebook
      url: https://www.fb.com/Tchouambou
    - title: linkedin
      url: https://www.linkedin.com/in/franckt

- name: Anton Lisovsky
  pic: anton
  position: Web Developer
  social:
    - title: twitter
      url: "https://twitter.com/xzarxzez"
    - title: github
      url: "https://github.com/antlis"
    - title: linkedin
      url: "#"

- name: Rinat Yahin
  pic: rinat
  position: iOS Developer
  social:
    - title: twitter
      url: "https://www.facebook.com/yahin.r.r"
    - title: facebook
      url: "https://twitter.com/_6234530394982"
    - title: linkedin
      url: "https://ru.linkedin.com/pub/rinat-yahin/b2/65b/ab4"

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: https://twitter.com/byrocketscience
  - title: facebook
    url: https://www.facebook.com/ByRocketScience
  - title: google-plus
    url: https://plus.google.com/105510692232230355051
  - title: instagram
    url: http://instagram.com/ByRocketScience

# Postal address (add as many lines as necessary)
address:
  - line: 308 Westover Avenue
  - line: Norfolk, VA 23507

# Build settings
markdown: kramdown
permalink: pretty
