url: https://byrocketscience.github.io
baseurl: 

# Site settings
title: Rocket Science
email: contact@byrocketscience.com
description: "Write an awesome description for your new site here. You can edit this line in _config.yml. It will appear in your document head meta (for Google search results) and in your feed.xml site description."

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: 26A69A
  secondary: 00695C
  secondary-dark: 333

# Team names, titles and social links
people:
- name: David Jenkins
  pic: david
  position: Project Lead Developer
  social:
    - title: twitter
      url: https://twitter.com/boarderdav
    - title: facebook
      url: https://www.facebook.com/boarderdav
    - title: linkedin
      url: https://www.linkedin.com/in/davidjenkinspe

- name: O'Neill Mateo
  pic: jose
  position: Android and Web Developer
  social:
    - title: twitter
      url: https://twitter.com/yomat3o
    - title: google-plus
      url: https://plus.google.com/+JoseMateoA/
    - title: linkedin
      url: http://www.linkedin.com/in/josemateoa

- name: Jake Spracher
  pic: jake
  position: iOS and Web Developer
  social:
    - title: twitter
      url: #
    - title: facebook
      url: #
    - title: google-plus
      url: #

- name: Franck Tchouambou
  pic: franck
  position: Growth Hacker & Business Developer
  social:
    - title: twitter
      url: #
    - title: facebook
      url: #
    - title: google-plus
      url: #	  

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: https://twitter.com/byrocketscience
  - title: facebook
    url: https://www.facebook.com/ByRocketScience
  - title: google-plus
    url: https://plus.google.com/105510692232230355051
  - title: instagram
    url: http://instagram.com/ByRocketScience

# Postal address (add as many lines as necessary)
address:
  - line: 308 Westover Avenue
  - line: Norfolk, VA 23507

# Build settings
markdown: kramdown
permalink: pretty